[bot]
botname = ""
environment = "dev"
retry = 3

[emails]
success_email = ""

[urls]
url = ""

[file_path]
input_file = ""
output_file = ""

[applications]
browser = ""

[applicaiton.path]
application_1 = ""
application_2 = ""
application_3 = ""

[api_keys]
api_key_1 = ""

[login_credentials]
application_username_1 = ""
application_password_1 = ""


[server]
host = ""
port = ""
ssl = ""

[database]
url = ""
name = ""
username = ""
passsword = ""
