[bot]
name = ""
environment = "dev"
email = "arnoldt2009@gmail.com"

[bot.urls]
url = ""

[server]
host = ""
port = ""
ssl = ""

[database]
url = ""
name = ""
username = ""
passsword = ""
